"""empty message

Revision ID: 121c501cbda2
Revises: 94211bfe5369
Create Date: 2017-09-14 11:39:54.966625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '121c501cbda2'
down_revision = '94211bfe5369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tags', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
