"""empty message

Revision ID: 94211bfe5369
Revises: ea27fe86e4b4
Create Date: 2017-09-14 11:39:15.621967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94211bfe5369'
down_revision = 'ea27fe86e4b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tags', sa.String(length=50), nullable=True))
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_column('user', 'tags')
    # ### end Alembic commands ###
